<a href="https://colab.research.google.com/github/Manav010203/Quiz/blob/cloudmain/TENSORS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.6.0+cu124


Introduction to tensors


In [ ]:
##scalar tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
##vector tensor
vector = torch.tensor([[7,7],[8,8]])
vector


tensor([[7, 7],
        [8, 8]])

In [ ]:
vector.ndim

2

In [ ]:
vector.shape

torch.Size([2, 2])

In [ ]:
#matrix

MATRIX = torch.tensor([[7,7],
                       [8,8]])
MATRIX

tensor([[7, 7],
        [8, 8]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 7])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
##TENSOR
TENSOR =torch.tensor([[[1,2,3],
                  [2,3,4],
                  [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]])

##RANDOM TENSOR

why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data
`start with random tensor -> look at the data -> update random numbers -> look at data -> update random numbers`

In [ ]:
#create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4271, 0.9966, 0.3135, 0.1658],
        [0.2685, 0.2914, 0.5461, 0.7356],
        [0.1994, 0.6062, 0.2011, 0.5497]])

In [ ]:
random_tensor.ndim

2

In [ ]:
##random tensor for similar shape of an image
random_tensor_image = torch.rand(224,224,3) #height,width,colourchannels(RGB)
random_tensor_image.shape , random_tensor_image.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
## zeros and ones tensor
zero = torch.zeros([3,4])
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones([3,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create tensor like
ten_zeros= torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATATYPE


In [ ]:
float_32_tensor = torch.tensor([3.0,4.0,5.0],
                               dtype=None,
                               device=None,
                               requires_grad=False
                               )
float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
tensor = float_16_tensor*float_32_tensor
tensor

tensor([ 9., 16., 25.])

In [ ]:
tensor.dtype

torch.float32

tensor attributes
1. Tensors not right datatypes=> to do get the datatype from a tensor, u can use `tensor.dtype`
2. Tensors not right shape=> to get the shape of the tensor use `tensor.shape`
3. Tensors are not on right device=> to get the device of the tensor,u can use `tensor.device`

In [ ]:
some_tensor = torch.rand(3,5)
some_tensor

tensor([[0.1252, 0.0812, 0.4355, 0.2413, 0.8382],
        [0.8125, 0.5715, 0.9504, 0.2466, 0.5953],
        [0.4641, 0.9798, 0.5318, 0.7069, 0.6213]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor is :{some_tensor.dtype}")
print(f" shape of the tensor is :{some_tensor.shape}")
print(f"device of the tensor : {some_tensor.device}")

tensor([[0.1252, 0.0812, 0.4355, 0.2413, 0.8382],
        [0.8125, 0.5715, 0.9504, 0.2466, 0.5953],
        [0.4641, 0.9798, 0.5318, 0.7069, 0.6213]])
Datatype of tensor is :torch.float32
 shape of the tensor is :torch.Size([3, 5])
device of the tensor : cpu


## MAnipulating tensors (tensor operations)

tensor operation include:
* Addition
* subtraction
* multiplication
* Division
* matrix Multiplication(dot product)

In [ ]:
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)
torch.add(tensor,10)
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [ ]:
tensor*tensor

tensor([1, 4, 9])

In [ ]:
#matrix multiplication
%%time
torch.matmul(tensor,tensor )

CPU times: user 852 µs, sys: 0 ns, total: 852 µs
Wall time: 830 µs


tensor(14)

In [ ]:
###One of the biggest error is shape error in matrix multiplication

%%time
tensor@tensor

CPU times: user 403 µs, sys: 61 µs, total: 464 µs
Wall time: 371 µs


tensor(14)

In [ ]:
t1 = torch.rand([4,3])
t1

tensor([[0.1297, 0.4015, 0.7812],
        [0.4361, 0.5494, 0.0486],
        [0.2708, 0.9882, 0.9629],
        [0.8096, 0.1949, 0.3828]])

In [ ]:
t2 = torch.rand([3,3])
t2

tensor([[0.2364, 0.4676, 0.3344],
        [0.0465, 0.0916, 0.5504],
        [0.5028, 0.7794, 0.6263]])

In [ ]:
torch.matmul(t1,t2)

tensor([[0.4421, 0.7063, 0.7537],
        [0.1531, 0.2921, 0.4787],
        [0.5941, 0.9676, 1.2376],
        [0.3929, 0.6947, 0.6177]])

In [ ]:
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensorB = torch.tensor([[6,7],
                        [8,9],
                        [11,10]])
ans = torch.matmul(tensorA,tensorB) ##ERROR


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensorA.shape , tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the shape error from a tensor use `transpose`
Transpose switches the axes or dimensions of a given tensor

In [ ]:
tensorA.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
tensorA @ tensorB.T

tensor([[ 20,  26,  31],
        [ 46,  60,  73],
        [ 72,  94, 115]])

Finding the min,max,mean,sum etc (tensor AGGREGATIOn)

In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))
##data type error

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

Finding the positional max and min

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping , stacking , squeezing and unsqueesing tensors
Reshaping => reshapes an input tensor to a defined Shape.
View => Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
stacking => combine multiple tensors on top of each other (vstack) or side by side (hstack)
Squezze => removes all 1 dimension from a tensor
Unsqueeze => add a 1 dimension to a target tensor
Permute => Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
##reshape
x_reshape = x.reshape(1,9)
x_reshape,x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
##view
z = x.view(1,9)
z,z.shape
##changes in z is is changes in x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
##stack
x_stacked = torch.stack([x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [ ]:
p=torch.zeros(2,1,2,1,2)
p

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
s = torch.squeeze(p,3)
s,s.size()

(tensor([[[[0., 0.],
           [0., 0.]]],
 
 
         [[[0., 0.],
           [0., 0.]]]]),
 torch.Size([2, 1, 2, 2]))

In [ ]:
q=torch.unsqueeze(s,3)
q,q.size()
#

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [ ]:
x.size()

torch.Size([9])

In [ ]:
##torch.permute

x_original = torch.rand(size=(224,224,3))
x_original.size()
x_permuted = x_original.permute(2,0,1)
# x_original.shape
x_permuted.shape

torch.Size([3, 224, 224])

##indexing
indexing with pytorch is similar to indexing with numpy

In [ ]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[0,:,2]

tensor([3, 6, 9])

##pytorch tensors and numpy


*  Data in Numpy, want in pytorch tensor-> `torch.from_numpy(ndarray)`
*  Pytorch tensor-> Numpy -> `torch.Tensor.numpy()`



In [ ]:
#numpy array to tensor
import torch
import numpy as np

array =np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the tensor and what happens to numpy_tensor
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Pytorch reproducibility (trying to take out random out of random)
In short how a neural network learns:

`starts with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

to reduce the radomness in neural network and pytorch comes the concept of random seed,
essentially what the random seed is "flavour" the randomness



In [ ]:
torch.rand(4,4)

tensor([[0.6436, 0.8068, 0.1860, 0.7027],
        [0.8278, 0.8072, 0.3201, 0.9646],
        [0.5368, 0.4327, 0.2334, 0.4760],
        [0.4895, 0.8842, 0.7792, 0.1983]])

In [ ]:
import torch
tensor_a=torch.rand(3,4)
tensor_b=torch.rand(3,4)
print(tensor_a)
print(tensor_b)
print(tensor_a==tensor_b)

tensor([[0.1675, 0.1844, 0.6813, 0.4566],
        [0.8229, 0.2024, 0.3177, 0.9919],
        [0.6244, 0.3675, 0.2931, 0.4793]])
tensor([[0.8387, 0.5832, 0.2161, 0.0463],
        [0.0472, 0.9306, 0.9757, 0.3122],
        [0.3602, 0.6103, 0.0478, 0.0502]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#let's make some random but reproducible tensors
import torch
#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_a=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_b=torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##running tensors and pytorch objects on the GPUs (and making faster computations)
GPUS = faster computation on numbers, thanks to CUDA +NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory(good)

In [ ]:
!nvidia-smi

Fri Mar 14 08:18:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

##checking for gpu acces in pytorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count the number of gpus
torch.cuda.device_count()

1

##Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
#create a tensor
tensor =torch.tensor([1,2,3])
#tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
 #move tensor to gpu if available
 tensor_on_gpu = tensor.to(device)
 tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to CPU

In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

# to fix the GPU tensor with numpy issue, we can first set it to the cpu


In [ ]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

#EXERCISE

In [ ]:
import torch
tensor1 =torch.rand(7,7)
tensor1

tensor([[0.5328, 0.5303, 0.3715, 0.9881, 0.8350, 0.8608, 0.2742],
        [0.4966, 0.9610, 0.5999, 0.6665, 0.2326, 0.8942, 0.0105],
        [0.8812, 0.2647, 0.6096, 0.7584, 0.1550, 0.7796, 0.0946],
        [0.8887, 0.7975, 0.8681, 0.4704, 0.9498, 0.9650, 0.9163],
        [0.1412, 0.5600, 0.0570, 0.3431, 0.7668, 0.8993, 0.8902],
        [0.4717, 0.0433, 0.2252, 0.0062, 0.6836, 0.6948, 0.0174],
        [0.2440, 0.9454, 0.3904, 0.0696, 0.4178, 0.1390, 0.2612]])

In [ ]:
tensor2=torch.rand(1,7)
tensor_multi = torch.matmul(tensor1,tensor2.T)
tensor_multi

tensor([[3.3014],
        [2.8791],
        [2.4130],
        [3.9812],
        [2.5765],
        [1.5529],
        [1.7195]])

In [ ]:
torch.manual_seed(0)
tensor1_s=torch.rand(7,7)
tensor2_s=torch.rand(1,7)


In [ ]:
torch.manual_seed(0)
tensor_multi = torch.matmul(tensor1_s,tensor2_s.T)
tensor_multi

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
torch.cuda.manual_seed(1234)
tensor1_s=torch.rand(7,7)
tensor2_s=torch.rand(1,7)


In [ ]:
torch.cuda.manual_seed(1234)
tensor_multi = torch.matmul(tensor1_s,tensor2_s.T)
tensor_multi

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

In [ ]:
##6
import torch
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device using is {device}")

tensor_gpu_1 = torch.rand(2,3).to(device)
tensor_dpu_2 = torch.rand(2,3).to(device)

tensor_gpu_1,tensor_dpu_2


device using is cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
##7
import torch
torch.manual_seed(1234)
tensor_multi_gpu = torch.matmul(tensor_gpu_1,tensor_dpu_2.T)
tensor_multi_gpu,tensor_multi_gpu.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [ ]:
##8
max = tensor_multi_gpu.max()
max

tensor(0.5617, device='cuda:0')

In [ ]:
##8
min=tensor_multi_gpu.min()
min

tensor(0.3647, device='cuda:0')

In [ ]:
##9
max_index=tensor_multi_gpu.argmax()
max_index

tensor(3, device='cuda:0')

In [ ]:
##9
min_index = tensor_multi_gpu.argmin()

min_index

tensor(0, device='cuda:0')

In [ ]:
import torch
torch.manual_seed(7)
tensor_random = torch.rand(1,1,1,10)
tensor_random

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [ ]:
torch.manual_seed(7)
tensor_new = tensor_random.squeeze()
tensor_new,tensor_new.shape,tensor_random.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]),
 torch.Size([1, 1, 1, 10]))

In [ ]:
tensor_un=tensor_new.unsqueeze(dim=0)
tensor_un,tensor_un.shape


(tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
          0.8513]]),
 torch.Size([1, 10]))